# Generated by Django 4.2 on 2023-05-01 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Diagnosis", "0003_alter_crop_crop_img_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tagging",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                (
                    "write_date",
                    models.DateTimeField(auto_now=True, verbose_name="write_date"),
                ),
                ("is_agree", models.BooleanField(default=False)),
                ("comment", models.CharField(default=None, max_length=1024)),
                (
                    "crop_img_path",
                    models.ForeignKey(
                        db_column="crop_img_path",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Diagnosis.crop",
                    ),
                ),
                (
                    "doctor",
                    models.OneToOneField(
                        db_column="doctor",
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interpretation",
            fields=[
                ("idx", models.AutoField(primary_key=True, serialize=False)),
                (
                    "write_date",
                    models.DateTimeField(auto_now=True, verbose_name="write_date"),
                ),
                ("interpretation", models.CharField(max_length=1024)),
                (
                    "patient",
                    models.ForeignKey(
                        db_column="patient",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Diagnosis.patient",
                    ),
                ),
            ],
        ),
    ]
