# Generated by Django 4.2 on 2023-05-01 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ResultDetail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagging",
            name="doctor",
            field=models.ForeignKey(
                db_column="doctor",
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
