# Generated by Django 4.2 on 2023-04-27 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="img_path",
            field=models.ForeignKey(
                db_column="img_path",
                on_delete=django.db.models.deletion.CASCADE,
                to="Diagnosis.imagepath",
            ),
        ),
        migrations.AlterField(
            model_name="imagepath",
            name="patient",
            field=models.ForeignKey(
                db_column="patient",
                on_delete=django.db.models.deletion.CASCADE,
                to="Diagnosis.patient",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                db_column="doctor",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
