# Generated by Django 4.2 on 2023-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Diagnosis", "0002_alter_crop_img_path_alter_imagepath_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="crop_img_path",
            field=models.ImageField(blank=True, max_length=1024, upload_to=""),
        ),
    ]
