# Generated by Django 4.2.1 on 2023-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0003_alter_crop_crop_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('imgfile', models.FileField(upload_to='dicom_files/')),
                ('imgfile2', models.FileField(upload_to='dicom_files/')),
                ('converted_file', models.ImageField(blank=True, null=True, upload_to='png_files/')),
                ('converted_file2', models.ImageField(blank=True, null=True, upload_to='png_files/')),
            ],
        ),
    ]
