# Generated by Django 4.2.1 on 2023-06-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0004_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
