# Generated by Django 4.2.1 on 2023-09-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0006_convertedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConvertedFile',
        ),
    ]
