# Generated by Django 4.2.1 on 2023-09-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0007_delete_convertedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcm_file', models.FileField(upload_to='dcm_files/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='image_files/')),
            ],
        ),
    ]
